# Generated by Django 4.1.6 on 2023-09-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0008_employee_attendance_alter_attendance_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tax', models.FloatField()),
                ('nssf', models.FloatField()),
                ('nhif', models.FloatField()),
                ('others', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PayRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.FloatField()),
                ('expected_hours', models.FloatField()),
                ('deductions', models.FloatField()),
                ('leave_days', models.FloatField()),
                ('gross_pay', models.FloatField()),
                ('net_pay', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.employee')),
            ],
        ),
    ]
