# Generated by Django 4.1.6 on 2023-10-09 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, null=True)),
                ('payroll_id', models.CharField(max_length=100, null=True)),
                ('employee_id', models.CharField(max_length=100, null=True)),
                ('sign_id', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('id_no', models.CharField(max_length=100, null=True)),
                ('pin_no', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('account_no', models.CharField(max_length=100, null=True)),
                ('basic_salary', models.FloatField(default=0.0)),
                ('allowance', models.FloatField(default=0.0)),
                ('add_ons', models.FloatField(default=0.0)),
                ('total_hours', models.FloatField(default=0.0)),
                ('leave_days', models.FloatField(default=0.0)),
                ('deductions', models.FloatField(default=0.0)),
                ('gross_pay', models.FloatField(default=0.0)),
                ('taxable_income', models.FloatField(default=0.0)),
                ('tax', models.FloatField(default=0.0)),
                ('nhif', models.FloatField(default=0.0)),
                ('nssf', models.FloatField(default=0.0)),
                ('insurance', models.FloatField(default=0.0)),
                ('housing', models.FloatField(default=0.0)),
                ('others', models.FloatField(default=0.0)),
                ('net_pay', models.FloatField(default=0.0)),
                ('created', models.DateField(default=datetime.date(2023, 10, 9))),
            ],
        ),
        migrations.CreateModel(
            name='PayRollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('tax_rate', models.TextField(default='24000=10%\n8333=25%\n467667=30%\n300000=32.5%\n')),
                ('nssf', models.FloatField()),
                ('nhif', models.FloatField()),
                ('health_insurance', models.FloatField(default=0.0)),
                ('housing', models.FloatField(default=0.0)),
                ('others', models.FloatField()),
            ],
        ),
    ]
