# Generated by Django 4.2.5 on 2023-11-02 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapayments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 8, 23, 27, 383931)),
        ),
    ]
