# Generated by Django 4.1.6 on 2023-09-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.FloatField()),
                ('tax_rate', models.FloatField()),
                ('nssf', models.FloatField()),
                ('nhif', models.FloatField()),
                ('health_insurance', models.FloatField(default=0.0)),
                ('housing', models.FloatField(default=0.0)),
                ('others', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='PayRollSettings',
        ),
        migrations.AddField(
            model_name='payroll',
            name='payroll_id',
            field=models.CharField(default=-1864371111369181787, max_length=1000),
        ),
    ]
