# Generated by Django 4.1.6 on 2023-10-11 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(default='audit', max_length=100),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='relief',
            field=models.FloatField(default=2400.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created',
            field=models.DateField(default=datetime.date(2023, 10, 11)),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='tax_rate',
            field=models.TextField(default='24000=10%,8333=25%,467667=30%,300000=32.5%'),
        ),
    ]
