# Generated by Django 4.2.5 on 2023-11-25 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll_Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhif_rates_file', models.FileField(upload_to='nhif_files')),
                ('nhif_relief_rate', models.FloatField(default=15.0)),
                ('nssf_rate', models.FloatField(default=6.0)),
                ('house_levy_rate', models.FloatField(default=1.5)),
                ('paye_rates', models.FileField(upload_to='paye_files')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
