# Generated by Django 4.1.6 on 2023-09-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollsetting_delete_payrollsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='payroll_id',
            field=models.CharField(default=-393528598436759637, max_length=1000),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='tax_rate',
            field=models.TextField(default='\n24000=10%\n8333=25%\n467667=30%\n300000=32.5%\n'),
        ),
    ]
