# Generated by Django 4.2.5 on 2023-11-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll_rates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsetting',
            name='health_insurance',
        ),
        migrations.RemoveField(
            model_name='payrollsetting',
            name='housing',
        ),
        migrations.RemoveField(
            model_name='payrollsetting',
            name='nhif',
        ),
        migrations.RemoveField(
            model_name='payrollsetting',
            name='others',
        ),
    ]
