# Generated by Django 4.2.7 on 2023-11-04 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_extrapayments_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapayments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 14, 17, 9, 380236)),
        ),
    ]
