# Generated by Django 4.2.5 on 2023-10-25 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_extrapayments_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapayments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 12, 14, 21, 781395)),
        ),
    ]
