# Generated by Django 4.2.7 on 2023-12-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_payrollsetting_health_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapayments',
            name='modified_absentee_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='extrapayments',
            name='unpaid_leave_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
