# Generated by Django 4.1.6 on 2023-10-14 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payroll_pay_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='created',
            field=models.DateField(default=datetime.date(2023, 10, 14)),
        ),
    ]
