# Generated by Django 4.1.6 on 2023-09-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payroll_payroll_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='payroll_id',
            field=models.CharField(default=5718200865053104859, max_length=1000),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='tax_rate',
            field=models.TextField(default='24000=10%\n8333=25%\n467667=30%\n300000=32.5%\n'),
        ),
    ]
