# Generated by Django 4.2.5 on 2023-11-08 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_extrapayments_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapayments',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
