# Generated by Django 4.2.5 on 2023-11-10 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0004_alter_extrapayments_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPayRollSetting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('org_name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('tax_rate', models.TextField(default='24000=10%,8333=25%,467667=30%,300000=32.5%')),
                ('relief', models.DecimalField(decimal_places=2, default=2400.0, max_digits=10)),
                ('nssf', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nhif', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('health_insurance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('housing', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pay roll setting',
                'verbose_name_plural': 'historical pay roll settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPayRoll',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, null=True)),
                ('payroll_id', models.CharField(max_length=100, null=True)),
                ('employee_id', models.CharField(max_length=100, null=True)),
                ('sign_id', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('id_no', models.CharField(max_length=100, null=True)),
                ('pin_no', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('account_no', models.CharField(max_length=100, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('add_ons', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_days', models.FloatField(default=0.0)),
                ('overtime_hours', models.FloatField(default=0.0)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('incentives', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('leave_days', models.FloatField(default=0.0)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nhif', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nssf', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('housing', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('welfare_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('created_time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='audit', max_length=100)),
                ('pay_run', models.CharField(default='', max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pay roll',
                'verbose_name_plural': 'historical pay rolls',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExtraPayments',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('overtime_hours', models.FloatField(default=0.0)),
                ('overtime_rate', models.FloatField(default=0.0)),
                ('incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('performance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('awards', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('welfare_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical extra payments',
                'verbose_name_plural': 'historical extra paymentss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
