# Generated by Django 4.2.5 on 2023-10-16 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_payroll_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
