# Generated by Django 4.1.6 on 2023-10-01 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_payroll_payroll_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='expected_hours',
        ),
        migrations.AddField(
            model_name='payroll',
            name='account_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='add_ons',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='allowance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='basic_salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='created',
            field=models.DateField(default=datetime.date(2023, 10, 1)),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='housing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='id_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='insurance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='nhif',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='others',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='taxable_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deductions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='gross_pay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='leave_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_pay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payroll_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
