# Generated by Django 4.1.6 on 2023-10-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_remove_payroll_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='sign_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
