# Generated by Django 4.2.5 on 2023-10-18 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_remove_payroll_created_payroll_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
