# Generated by Django 4.1.6 on 2023-10-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payroll_nssf_payroll_pin_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='org_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
