# Generated by Django 4.2.5 on 2023-10-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_payroll_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100)),
                ('overtime_hours', models.FloatField(default=0.0)),
                ('overtime_rate', models.FloatField(default=0.0)),
                ('incentive', models.FloatField(default=0.0)),
                ('performance', models.FloatField(default=0.0)),
                ('awards', models.FloatField(default=0.0)),
            ],
        ),
    ]
