# Generated by Django 4.2.5 on 2023-10-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_extrapayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrapayments',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
