# Generated by Django 4.1.6 on 2023-10-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payrollsetting_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='org_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
