# Generated by Django 4.1.6 on 2023-10-02 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payroll_org_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='created',
            field=models.DateField(default=datetime.date(2023, 10, 2)),
        ),
    ]
