# Generated by Django 4.2.5 on 2023-10-24 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_alter_payroll_add_ons_alter_payroll_allowance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='total_hours',
            new_name='total_days',
        ),
        migrations.AddField(
            model_name='extrapayments',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='extrapayments',
            name='loan_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='extrapayments',
            name='welfare_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='incentives',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='extrapayments',
            name='awards',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='extrapayments',
            name='incentive',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='extrapayments',
            name='performance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
