# Generated by Django 4.1.6 on 2023-10-05 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_alter_payroll_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='created',
            field=models.DateField(default=datetime.date(2023, 10, 5)),
        ),
    ]
