# Generated by Django 4.2.5 on 2023-10-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_rename_total_hours_payroll_total_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='loan_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='welfare_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
