# Generated by Django 4.2.5 on 2023-09-17 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=10)),
                ('level', models.CharField(default='', max_length=10)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Approvers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ids', models.CharField(default='', max_length=100)),
                ('approval_type', models.CharField(default='', max_length=10)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=50)),
                ('hod', models.CharField(default='None', max_length=50)),
                ('size', models.FloatField(default=1)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=50)),
                ('requirements', models.CharField(default='None', max_length=50)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recpient_id', models.CharField(default='', max_length=30)),
                ('details', models.TextField()),
                ('links', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(default='', max_length=10)),
                ('details', models.TextField()),
                ('created', models.DateField()),
                ('documents', models.FileField(default='process.pdf', upload_to='process')),
                ('approvals', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='management.approvals')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('annual', 'annual'), ('sick', 'sick'), ('compassionate', 'compassionate'), ('office', 'office')], default='', max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('attachments', models.FileField(default='attachment.pdf', upload_to='leave')),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField()),
                ('Approvals_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave', to='management.approvals')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default='None', max_length=50)),
                ('first_name', models.CharField(default='None', max_length=50)),
                ('second_name', models.CharField(default='None', max_length=50)),
                ('id_no', models.CharField(default='None', max_length=50)),
                ('email', models.EmailField(default='None', max_length=254)),
                ('phone', models.CharField(default='None', max_length=50)),
                ('next_kin_name', models.CharField(default='None', max_length=50)),
                ('next_kin_id', models.CharField(default='None', max_length=50)),
                ('role', models.CharField(default='None', max_length=50)),
                ('department', models.CharField(default='None', max_length=50)),
                ('education_level', models.CharField(default='None', max_length=50)),
                ('documents', models.FileField(default='documents.pdf', upload_to='documents')),
                ('account_no', models.CharField(default='None', max_length=50)),
                ('bank_name', models.CharField(default='None', max_length=50)),
                ('salary', models.FloatField(default=0.0)),
                ('allowance', models.FloatField(default=0.0)),
                ('add_ons', models.FloatField(default=0.0)),
                ('finance_documents', models.FileField(default='documents.pdf', upload_to='bank_documents')),
                ('status', models.CharField(default='None', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leave', models.BooleanField(default=False)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField()),
                ('lat', models.CharField(default='', max_length=10)),
                ('long', models.CharField(default='', max_length=10)),
                ('lat1', models.CharField(default='', max_length=10)),
                ('lat2', models.CharField(default='', max_length=10)),
                ('image1', models.TextField()),
                ('image2', models.TextField()),
                ('remarks', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.employee')),
            ],
        ),
        migrations.AddField(
            model_name='approvals',
            name='approvers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.approvers'),
        ),
    ]
