# Generated by Django 4.1.6 on 2023-09-21 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empfiles',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empfiles',
            name='properties',
            field=models.TextField(default='none'),
        ),
    ]
