# Generated by Django 4.2.7 on 2023-11-04 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='office',
        ),
        migrations.AddField(
            model_name='employee',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.station'),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 11, 4, 10, 15, 41, 597524, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 11, 4, 10, 15, 41, 597493, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 10, 15, 41, 621264, tzinfo=datetime.timezone.utc)),
        ),
    ]
