# Generated by Django 4.2.5 on 2023-09-17 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='dol',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='emoloyee.png', upload_to='emp_images'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
