# Generated by Django 4.2.5 on 2023-10-25 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 9, 7, 49, 831247, tzinfo=datetime.timezone.utc)),
        ),
    ]
