# Generated by Django 4.1.6 on 2023-09-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_empfiles_created_alter_empfiles_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='empfiles',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.filescategory'),
        ),
    ]
