# Generated by Django 4.2.5 on 2023-10-25 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_chatmessage_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 9, 9, 44, 809796, tzinfo=datetime.timezone.utc)),
        ),
    ]
