# Generated by Django 4.2.5 on 2023-11-27 04:27

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_attsettings_end_alter_attsettings_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='template',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 11, 27, 4, 27, 7, 694410, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 11, 27, 4, 27, 7, 694410, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 4, 27, 7, 699446, tzinfo=datetime.timezone.utc)),
        ),
    ]
