# Generated by Django 4.1.6 on 2023-10-09 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_applications_end_alter_applications_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='hod',
            new_name='hod_username',
        ),
        migrations.AlterField(
            model_name='applications',
            name='end',
            field=models.DateField(default=datetime.datetime(2023, 10, 9, 8, 13, 37, 191238)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 10, 9, 8, 13, 37, 191238)),
        ),
    ]
