# Generated by Django 4.1.6 on 2023-09-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_filescategory_alter_empfiles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empfiles',
            name='document',
            field=models.FileField(default='document.pdf', upload_to='emp_files'),
        ),
    ]
