# Generated by Django 4.2.5 on 2023-10-25 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_chatmessage_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 9, 14, 21, 791959, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='departments',
            field=models.CharField(choices=[('sales department', 'sales department'), ('HR department', 'HR department')], default='None', max_length=50),
        ),
    ]
