# Generated by Django 4.2.5 on 2023-11-08 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_attsettings_end_alter_attsettings_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 11, 8, 4, 32, 49, 208849, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 11, 8, 4, 32, 49, 208849, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 4, 32, 49, 213836, tzinfo=datetime.timezone.utc)),
        ),
    ]
