# Generated by Django 4.1.6 on 2023-10-09 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_hod_department_hod_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='end',
            field=models.DateField(default=datetime.datetime(2023, 10, 9, 8, 14, 44, 18586)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 10, 9, 8, 14, 44, 18586)),
        ),
    ]
