# Generated by Django 4.2.5 on 2023-11-10 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_attsettings_end_alter_attsettings_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('undisclosed', 'undisclosed')], default='undisclosed', max_length=100),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 11, 10, 5, 15, 36, 605227, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 11, 10, 5, 15, 36, 605227, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 5, 15, 36, 605227, tzinfo=datetime.timezone.utc)),
        ),
    ]
