# Generated by Django 4.1.6 on 2023-09-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_empfiles_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='empfiles',
            name='file_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
