# Generated by Django 4.1.6 on 2023-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_applications_end_alter_applications_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='days',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='end',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='start',
        ),
        migrations.AlterField(
            model_name='employee',
            name='departments',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
