# Generated by Django 4.2.5 on 2023-09-20 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_attendance_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('deduction_per_hour', models.FloatField()),
                ('morning_deduction', models.FloatField()),
                ('evening_deduction', models.FloatField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='lat2',
            new_name='long1',
        ),
        migrations.AddField(
            model_name='attendance',
            name='counts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2023, 9, 20)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='partial', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
