# Generated by Django 4.1.6 on 2023-09-22 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_empfiles_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='next_kin_phone',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2023, 9, 22)),
        ),
    ]
