# Generated by Django 4.2.5 on 2023-11-10 14:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_historicalpayrollsetting_historicalpayroll_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0005_employee_gender_alter_attsettings_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 11, 10, 14, 1, 32, 683742, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 11, 10, 14, 1, 32, 683742, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 14, 1, 32, 699367, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dol',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('emp_id', models.CharField(default='None', max_length=50)),
                ('first_name', models.CharField(default='None', max_length=50)),
                ('second_name', models.CharField(default='None', max_length=50)),
                ('national_no', models.CharField(default='None', max_length=50)),
                ('kra_pin', models.CharField(default='None', max_length=50)),
                ('email', models.EmailField(default='None', max_length=254)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('undisclosed', 'undisclosed')], default='undisclosed', max_length=100)),
                ('phone', models.CharField(default='None', max_length=50)),
                ('next_kin_name', models.CharField(default='None', max_length=50)),
                ('next_kin_id', models.CharField(default='None', max_length=50)),
                ('next_kin_phone', models.CharField(default='None', max_length=50)),
                ('address', models.CharField(default='None', max_length=50)),
                ('location', models.CharField(default='None', max_length=50)),
                ('education_level', models.CharField(default='None', max_length=50)),
                ('doj', models.DateField(default=django.utils.timezone.now)),
                ('dol', models.DateField(null=True)),
                ('account_no', models.CharField(default='None', max_length=50)),
                ('bank_name', models.CharField(default='None', max_length=50)),
                ('salary', models.FloatField(default=0.0)),
                ('allowance', models.FloatField(default=0.0)),
                ('add_ons', models.FloatField(default=0.0)),
                ('other_fields', models.TextField(default='name:value')),
                ('status', models.CharField(choices=[('incomplete', 'incomplete'), ('active', 'active'), ('resigned', 'resigned'), ('terminated', 'terminated'), ('suspended', 'suspended')], default='None', max_length=50)),
                ('image', models.TextField(default='emoloyee.png', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('departments', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payroll_settings', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.payrollsetting')),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.roles')),
                ('station', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.station')),
            ],
            options={
                'verbose_name': 'historical employee',
                'verbose_name_plural': 'historical employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAttendance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_leave', models.BooleanField(default=False)),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('clock_in', models.CharField(default='', max_length=1000)),
                ('clock_out', models.CharField(default='', max_length=1000)),
                ('lat', models.CharField(default='', max_length=10)),
                ('long', models.CharField(default='', max_length=10)),
                ('lat1', models.CharField(default='', max_length=10)),
                ('long1', models.CharField(default='', max_length=10)),
                ('image1', models.TextField()),
                ('image2', models.TextField()),
                ('status', models.CharField(default='partial', max_length=100)),
                ('counts', models.IntegerField(default=0)),
                ('hours', models.FloatField(default=0.0)),
                ('days', models.FloatField(default=0.0)),
                ('leave_days', models.IntegerField(default=21)),
                ('deductions', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical attendance',
                'verbose_name_plural': 'historical attendances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
