# Generated by Django 4.2.5 on 2023-09-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_attsettings_rename_lat2_attendance_long1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attsettings',
            name='half_day',
            field=models.TimeField(default=(2023, 9, 20, 12, 53, 14, 2, 263, 0)),
        ),
    ]
