# Generated by Django 4.1.6 on 2023-09-22 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0006_employee_next_kin_phone_alter_attendance_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('attachment', models.FileField(default='attachment', upload_to='ápproval_files')),
                ('remarks', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='level',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='type',
        ),
        migrations.RemoveField(
            model_name='process',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='approvers',
        ),
        migrations.AlterField(
            model_name='process',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Approvers',
        ),
        migrations.AddField(
            model_name='applications',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.approvals'),
        ),
        migrations.AddField(
            model_name='approvals',
            name='approvers',
            field=models.ManyToManyField(to='management.employee'),
        ),
        migrations.AlterField(
            model_name='process',
            name='approvals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='management.applications'),
        ),
    ]
