# Generated by Django 4.2.5 on 2023-09-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_attsettings_half_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attsettings',
            name='half_day',
            field=models.TimeField(default='12:00'),
        ),
    ]
