# Generated by Django 4.1.6 on 2023-09-23 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_applications_rename_level_approvals_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.attsettings'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2023, 9, 23)),
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
