# Generated by Django 4.1.6 on 2023-10-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_attendance_day_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('active', 'active'), ('resigned', 'resigned'), ('terminated', 'terminated'), ('suspended', 'suspended')], default='None', max_length=50),
        ),
    ]
