# Generated by Django 4.2.5 on 2023-10-16 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
