# Generated by Django 4.2.5 on 2023-09-20 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_attsettings_half_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attsettings',
            name='half_day',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
