# Generated by Django 4.2.5 on 2023-12-07 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_attsettings_end_alter_attsettings_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='attachment',
            field=models.FileField(null=True, upload_to='mail_files'),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 12, 7, 11, 29, 1, 495621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 12, 7, 11, 29, 1, 495621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 11, 29, 1, 495621, tzinfo=datetime.timezone.utc)),
        ),
    ]
