# Generated by Django 4.2.5 on 2023-11-14 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_employee_remarks_historicalemployee_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 11, 14, 5, 3, 46, 573529, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 11, 14, 5, 3, 46, 573529, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 5, 3, 46, 579632, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='remarks',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='remarks',
            field=models.TextField(default='', null=True),
        ),
    ]
