# Generated by Django 4.1.6 on 2023-09-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_employee_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attsettings',
            old_name='deduction_per_hour',
            new_name='deduction_per_minute',
        ),
        migrations.RemoveField(
            model_name='attsettings',
            name='expected_hours',
        ),
    ]
