# Generated by Django 4.2.5 on 2023-12-08 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_mailmessage_attachment_alter_attsettings_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 12, 8, 4, 32, 39, 407403, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 12, 8, 4, 32, 39, 407403, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 4, 32, 39, 407403, tzinfo=datetime.timezone.utc)),
        ),
    ]
