# Generated by Django 4.2.5 on 2023-10-17 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_attendance_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applications',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applications',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='applications',
            name='attachment',
            field=models.FileField(default='attachment', upload_to='approval_files'),
        ),
    ]
