# Generated by Django 4.2.5 on 2023-09-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_attsettings_half_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attsettings',
            name='half_day',
            field=models.CharField(default='12:00:00', max_length=20),
        ),
    ]
