# Generated by Django 4.2.5 on 2023-10-21 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_applications_days_applications_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('anonymous', models.BooleanField(default=False)),
                ('sent', models.DateTimeField(default=datetime.datetime(2023, 10, 21, 5, 49, 0, 660729, tzinfo=datetime.timezone.utc))),
                ('seen', models.BooleanField(default=False)),
                ('file', models.FileField(null=True, upload_to='chat_files')),
                ('recep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_recepient', to='management.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to='management.profile')),
            ],
        ),
    ]
