# Generated by Django 4.2.7 on 2023-12-09 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_mailmessage_label_mailmessage_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='masked_sender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 12, 9, 11, 50, 47, 11452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 12, 9, 11, 50, 47, 11431, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 11, 50, 47, 20226, tzinfo=datetime.timezone.utc)),
        ),
    ]
