# Generated by Django 4.1.6 on 2023-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_deduction_per_hour_attsettings_deduction_per_minute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id_no',
            new_name='national_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Attendance',
        ),
        migrations.AddField(
            model_name='attsettings',
            name='employee_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
