# Generated by Django 4.1.6 on 2023-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_rename_id_no_employee_national_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.FloatField(default=0),
        ),
    ]
