# Generated by Django 4.2.7 on 2023-11-15 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_attsettings_end_alter_attsettings_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attsettings',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 11, 15, 4, 34, 41, 888601, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 11, 15, 4, 34, 41, 888574, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 4, 34, 41, 899636, tzinfo=datetime.timezone.utc)),
        ),
    ]
