# Generated by Django 4.2.5 on 2023-10-21 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_chatmessage_body_alter_chatmessage_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='anonymous_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_sender', to='management.profile'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 10, 18, 48, 510706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.jpeg', upload_to='profile_images'),
        ),
    ]
