# Generated by Django 4.2.7 on 2023-12-27 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_attsettings_end_alter_attsettings_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='lat',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lat1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='long',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='long1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 12, 27, 8, 19, 39, 962485, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 12, 27, 8, 19, 39, 962442, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 8, 19, 39, 995220, tzinfo=datetime.timezone.utc)),
        ),
    ]
