# Generated by Django 4.2.5 on 2023-10-22 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_chatmessage_anonymous_sender_alter_chatmessage_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 5, 33, 16, 757695, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='empfiles',
            name='employee',
            field=models.CharField(max_length=100),
        ),
    ]
