# Generated by Django 4.2.7 on 2023-12-31 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_attendance_lat_alter_attendance_lat1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attsettings',
            name='compassionate_leave_days',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='attsettings',
            name='sick_leave_days',
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name='department',
            name='approvers',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 12, 31, 7, 22, 27, 869347, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 12, 31, 7, 22, 27, 869324, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 7, 22, 27, 878778, tzinfo=datetime.timezone.utc)),
        ),
    ]
