# Generated by Django 4.1.6 on 2023-09-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_attendance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='deductions',
            field=models.FloatField(default=0.0),
        ),
    ]
