# Generated by Django 4.1.6 on 2023-09-25 10:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_attendance_deductions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2023, 9, 25)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='attachments',
            field=models.FileField(default='attachment.pdf', upload_to='application_files'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
