# Generated by Django 4.2.5 on 2023-10-22 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_chatmessage_sent_alter_empfiles_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='leave_days',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='attsettings',
            name='leave_days',
            field=models.FloatField(default=21.0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 6, 40, 16, 941354, tzinfo=datetime.timezone.utc)),
        ),
    ]
