# Generated by Django 4.2.7 on 2024-01-03 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_applications_category_alter_attsettings_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Applications', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='approvals',
            options={'verbose_name': 'Approvals', 'verbose_name_plural': 'Approvals'},
        ),
        migrations.AlterModelOptions(
            name='approvaltrack',
            options={'verbose_name': 'Approval Track', 'verbose_name_plural': 'Approval Track'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterModelOptions(
            name='attsettings',
            options={'verbose_name': 'Attendance Settings', 'verbose_name_plural': 'Attendance Settings'},
        ),
        migrations.AlterModelOptions(
            name='empfiles',
            options={'verbose_name': 'Employee File', 'verbose_name_plural': 'Employees Files'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='filescategory',
            options={'verbose_name': 'Files Category', 'verbose_name_plural': 'Files Categories'},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name': 'Leave', 'verbose_name_plural': 'Leave'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Roles', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='leave',
            name='remaining_leave_days',
            field=models.FloatField(default=21.0),
        ),
        migrations.AddField(
            model_name='leave',
            name='work_assignment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2024, 1, 3, 19, 38, 0, 787036, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2024, 1, 3, 19, 38, 0, 786870, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 19, 38, 0, 808613, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='category',
            field=models.CharField(choices=[('annual', 'annual'), ('sick', 'sick'), ('compassionate', 'compassionate'), ('unpaid', 'unpaid')], default='', max_length=100),
        ),
    ]
