# Generated by Django 4.1.6 on 2023-09-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_attendance_day_alter_leave_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='approvers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='applications',
            name='stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('complete', 'complete')], default='pending', max_length=10),
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='approvers',
        ),
        migrations.AddField(
            model_name='approvals',
            name='approvers',
            field=models.TextField(default=''),
        ),
    ]
