# Generated by Django 4.2.5 on 2023-10-23 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_attendance_leave_days_attsettings_leave_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 12, 0, 0, 345152, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='departments',
            field=models.CharField(choices=[('sales department', 'sales department'), ('HR department', 'HR department')], default='None', max_length=50),
        ),
    ]
