# Generated by Django 4.1.6 on 2023-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_applications_approvers_applications_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='expected',
            field=models.IntegerField(default=0),
        ),
    ]
