# Generated by Django 4.1.6 on 2023-09-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_applications_expected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='remarks',
            new_name='details',
        ),
    ]
