# Generated by Django 4.2.5 on 2023-10-23 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_chatmessage_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 12, 11, 15, 669364, tzinfo=datetime.timezone.utc)),
        ),
    ]
