# Generated by Django 4.1.6 on 2023-09-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_rename_remarks_leave_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='attachments',
            field=models.FileField(default='process.pdf', upload_to='application_files'),
        ),
        migrations.AlterField(
            model_name='process',
            name='approvals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='management.approvals'),
        ),
    ]
