# Generated by Django 4.2.5 on 2023-10-23 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_chatmessage_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='other_fields',
            field=models.TextField(default='name:value'),
        ),
        migrations.AddField(
            model_name='events',
            name='files',
            field=models.FileField(default='posts.png', upload_to='posts_files'),
        ),
        migrations.AddField(
            model_name='events',
            name='viewers',
            field=models.CharField(choices=[('all', 'all'), ('members', 'members'), ('admins', 'admins')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 18, 21, 20, 686682, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('announcement', 'announcement'), ('events', 'events'), ('updates', 'updates')], default='', max_length=100),
        ),
    ]
