# Generated by Django 4.2.7 on 2024-01-04 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_notifications_details_alter_attsettings_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='application',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2024, 1, 4, 18, 15, 11, 265192, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2024, 1, 4, 18, 15, 11, 265161, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 18, 15, 11, 276121, tzinfo=datetime.timezone.utc)),
        ),
    ]
