# Generated by Django 4.2.7 on 2024-01-04 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_notifications_application_alter_attsettings_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2024, 1, 4, 20, 58, 55, 566377, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2024, 1, 4, 20, 58, 55, 566348, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 20, 58, 55, 576042, tzinfo=datetime.timezone.utc)),
        ),
    ]
