# Generated by Django 4.2.5 on 2023-10-24 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_employee_other_fields_events_files_events_viewers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 4, 44, 5, 953153, tzinfo=datetime.timezone.utc)),
        ),
    ]
