# Generated by Django 4.1.6 on 2023-09-27 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_attendance_day_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attsettings',
            name='clock_in_latitude',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='attsettings',
            name='clock_in_longitude',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2023, 9, 27)),
        ),
    ]
