# Generated by Django 4.2.5 on 2024-01-07 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_attsettings_end_alter_attsettings_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2024, 1, 7, 10, 9, 51, 827898, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2024, 1, 7, 10, 9, 51, 827865, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 10, 9, 51, 850121, tzinfo=datetime.timezone.utc)),
        ),
    ]
