# Generated by Django 4.2.5 on 2023-10-24 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_chatmessage_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 8, 33, 4, 225998, tzinfo=datetime.timezone.utc)),
        ),
    ]
