# Generated by Django 4.1.6 on 2023-09-28 05:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollsetting_delete_payrollsettings_and_more'),
        ('management', '0021_attsettings_clock_in_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payroll_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.payrollsetting'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2023, 9, 28)),
        ),
    ]
