# Generated by Django 4.2.5 on 2024-01-07 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_attendance_clock_in_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_distance',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out_distance',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='end',
            field=models.TimeField(default=datetime.datetime(2024, 1, 7, 10, 14, 51, 803065, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attsettings',
            name='start',
            field=models.TimeField(default=datetime.datetime(2024, 1, 7, 10, 14, 51, 803005, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 10, 14, 51, 821049, tzinfo=datetime.timezone.utc)),
        ),
    ]
