# Generated by Django 4.1.6 on 2023-09-30 05:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_employee_payroll_settings_alter_attendance_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2023, 9, 30)),
        ),
    ]
