# Generated by Django 4.2.5 on 2023-10-24 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_chatmessage_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='viewers_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 47, 59, 767627, tzinfo=datetime.timezone.utc)),
        ),
    ]
