# Generated by Django 4.1.6 on 2023-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_alter_attendance_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attsettings',
            old_name='deduction_per_minute',
            new_name='deduction_per_day',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='attsettings',
            name='clock_in_latitude',
        ),
        migrations.RemoveField(
            model_name='attsettings',
            name='clock_in_longitude',
        ),
        migrations.RemoveField(
            model_name='attsettings',
            name='evening_deduction',
        ),
        migrations.RemoveField(
            model_name='attsettings',
            name='morning_deduction',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='payroll_settings',
        ),
        migrations.AddField(
            model_name='employee',
            name='kra_pin',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
