# Generated by Django 4.1.6 on 2023-10-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_rename_deduction_per_minute_attsettings_deduction_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attsettings',
            name='latitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='attsettings',
            name='longitude',
            field=models.CharField(default='', max_length=100),
        ),
    ]
