# Generated by Django 4.1.6 on 2023-10-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_attsettings_latitude_attsettings_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attsettings',
            name='expected_days',
            field=models.FloatField(default=24.0),
        ),
    ]
