# Generated by Django 4.1.6 on 2023-10-01 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_attsettings_max_distance_attsettings_max_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
