# Generated by Django 4.1.6 on 2023-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_remove_attsettings_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='kra_pin',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
