# Generated by Django 4.1.6 on 2023-10-05 04:07

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_alter_attendance_created_alter_attendance_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='created',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='applications',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2023, 10, 5)),
        ),
    ]
