# Generated by Django 4.1.6 on 2023-10-05 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_rename_created_applications_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvalTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='no comment')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.applications')),
            ],
        ),
    ]
