# Generated by Django 4.1.6 on 2023-10-06 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_approvaltrack_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2023, 10, 6)),
        ),
    ]
