# Generated by Django 4.1.6 on 2023-10-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
