# Generated by Django 4.1.6 on 2023-10-07 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_notifications_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='applications',
            name='end',
            field=models.DateField(default=datetime.datetime(2023, 10, 7, 10, 37, 15, 249456)),
        ),
        migrations.AddField(
            model_name='applications',
            name='start',
            field=models.DateField(default=datetime.datetime(2023, 10, 7, 10, 37, 15, 249384)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2023, 10, 7)),
        ),
    ]
